version: '3.8'
services:

  db:
    image: mysql:5.7
    env_file:
      - .env-non-dev
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
    command: ["python", "wsgi.py", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A src.tasks.celery worker --loglevel=info
    # command: celery -A src.tasks.celery worker --loglevel=debug
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379


volumes:
  db_data:
