version: '3.8'
services:

  db:
    image: mysql:5.7
    env_file:
      - .env-non-dev
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  web:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis

volumes:
  db_data:
